redone

diff --git a/web_stack_debugging_2/0-iamsomeoneelse b/web_stack_debugging_2/0-iamsomeoneelse
--- a/web_stack_debugging_2/0-iamsomeoneelse
+++ b/web_stack_debugging_2/0-iamsomeoneelse
@@ -1,3 +1,9 @@
 #!/usr/bin/env bash
-# Runs the whoami command under the user passed as argument.
-sudo -u "$1" whoami
+# This script runs the whoami command as the user passed as an argument
+
+if id "$1" &>/dev/null; then
+    sudo -u "$1" whoami
+else
+    echo "Error: User $1 does not exist"
+    exit 1
+fi
