000

diff --git a/load_balancer/0-custom_http_response_header b/load_balancer/0-custom_http_response_header
--- a/load_balancer/0-custom_http_response_header
+++ b/load_balancer/0-custom_http_response_header
@@ -1,48 +1,81 @@
 #!/usr/bin/env bash
-# This script configures Nginx to include a custom HTTP header X-Served-By
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-# Update packages
-apt-get -y update
-apt-get -y install nginx
+# Uncomment to see the script run in action
+#set -x
 
-# Create directory structure if it doesn't exist
-mkdir -p /var/www/html
+echo -e "Updating and doing some minor checks...\n"
 
-# Create index page
-echo "Hello World!" > /var/www/html/index.html
+function install() {
+    if ! command -v "$1" &> /dev/null; then
+        echo -e "    Installing: $1\n"
+        sudo apt-get update -y -qq && \
+            sudo apt-get install -y "$1" -qq
+        echo -e "\n"
+    else
+        echo -e "    ${1} is already installed.\n"
+    fi
+}
 
-# Create error page
-echo "Ceci n'est pas une page" > /var/www/html/404.html
+install nginx # install nginx
 
-# Get hostname
-HOSTNAME=$(hostname)
+echo -e "\nSetting up some minor stuff.\n"
 
-# Configure Nginx with custom header in the http block to apply to all requests
-sed -i "/http {/a \        add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/nginx.conf
+# Allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
 
-# Ensure the configuration is correct
-cat > /etc/nginx/sites-available/default << EOF
-server {
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+else
+    sudo mkdir -p /var/www
+    sudo chown -R "$USER":"$USER" /var/www
+    sudo chmod -R 755 /var/www
+fi
+
+# Create directories if not present
+for dir in /var/www/{html,error}; do
+    if ! [ -d "$dir" ]; then
+        sudo mkdir -p "$dir"
+    fi
+done
+
+# Creating new index
+echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
+
+# Create new error page
+echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
+
+# Backup default server config file
+sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/nginx-sites-enabled_default.backup
+
+# Create new server configuration
+server_config="server {
     listen 80 default_server;
     listen [::]:80 default_server;
-    
     root /var/www/html;
-    index index.html index.htm index.nginx-debian.html;
+    index index.html index.htm;
     server_name _;
-    
+    add_header X-Served-By \$hostname;
     location / {
         try_files \$uri \$uri/ =404;
     }
-    
-    error_page 404 /404.html;
-    location /404.html {
+    if (\$request_filename ~ redirect_me) {
+        rewrite ^ https://th3-gr00t.tk/ permanent;
+    }
+    error_page 404 /error_404.html;
+    location = /error_404.html {
         internal;
     }
-}
-EOF
+}"
 
-# Test Nginx configuration
-nginx -t
+echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null
 
-# Restart Nginx service
-service nginx restart
+# Start or restart nginx
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+    sudo service nginx start
+else
+    sudo service nginx restart
+fi
